name: vy_lock
version: 0.1.2
description: Simple function for forcing one at a time acces to a method (mutex)

dev_dependencies:
  pedantic: 1.8.0
  synchronized: any
  test: ^1.6.0

environment:
  sdk: ">=2.3.0 <3.0.0"
