name: vy_lock
description: Simple function for forcing one at a time acces to a method (mutex)
version: 0.2.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.16.4
  lints: ^2.0.0
  synchronized: any
